FROM adoptopenjdk/openjdk11:alpine-jre
LABEL maintainer = "it.testproj"

VOLUME /tmp

ADD target/swagger-project-template.jar app.jar
ENTRYPOINT [ "sh", "-c", "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]